version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: newdb
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: 1234qwer
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  